In [ ]:
import pandas as pd
import numpy as np

train_data = pd.read_csv("train.csv")

          id Sex  Length  Diameter  Height  Whole weight  Whole weight.1  \
0          0   F   0.550     0.430   0.150        0.7715          0.3285   
1          1   F   0.630     0.490   0.145        1.1300          0.4580   
2          2   I   0.160     0.110   0.025        0.0210          0.0055   
3          3   M   0.595     0.475   0.150        0.9145          0.3755   
4          4   I   0.555     0.425   0.130        0.7820          0.3695   
...      ...  ..     ...       ...     ...           ...             ...   
90610  90610   M   0.335     0.235   0.075        0.1585          0.0685   
90611  90611   M   0.555     0.425   0.150        0.8790          0.3865   
90612  90612   I   0.435     0.330   0.095        0.3215          0.1510   
90613  90613   I   0.345     0.270   0.075        0.2000          0.0980   
90614  90614   I   0.425     0.325   0.100        0.3455          0.1525   

       Whole weight.2  Shell weight  Rings  
0              0.1465        0.2400     11

In [ ]:
import ISLP
from ISLP.models import ModelSpec as MS
from ISLP.models import summarize
import statsmodels.api as sm

cols = train_data.columns.drop(['Sex', 'Rings'])
MS_x = MS(cols).fit(train_data)
x = MS_x.transform(train_data)
y = train_data['Rings']
model = sm.OLS(y,x)
result = model.fit()
summarize(result)

coef       std err        t  P>|t|
intercept       2.853000e+00  5.500000e-02   51.710   0.00
id             -5.006000e-07  2.550000e-07   -1.961   0.05
Length         -2.515400e+00  4.040000e-01   -6.224   0.00
Diameter        9.750600e+00  5.000000e-01   19.501   0.00
Height          2.237810e+01  4.900000e-01   45.661   0.00
Whole weight    3.858500e+00  1.210000e-01   31.780   0.00
Whole weight.1 -1.610240e+01  1.510000e-01 -106.592   0.00
Whole weight.2 -6.325600e+00  2.960000e-01  -21.387   0.00
Shell weight    2.095510e+01  2.200000e-01   95.427   0.00

In [ ]:
test_data = pd.read_csv("test.csv")
test_cols = test_data.columns.drop('Sex')
test_data2 = test_data[test_cols]
new_x = MS_x.transform(test_data2)
pred = result.get_prediction(new_x)
pred.predicted_mean

array([ 8.42304375,  9.87653435, 10.06291952, ..., 11.34111866,
       13.62854797,  8.16281878])

In [ ]:
test_data['Rings'] = pred.predicted_mean
print(test_data)

           id Sex  Length  Diameter  Height  Whole weight  Whole weight.1  \
0       90615   M   0.645     0.475   0.155        1.2380          0.6185   
1       90616   M   0.580     0.460   0.160        0.9830          0.4785   
2       90617   M   0.560     0.420   0.140        0.8395          0.3525   
3       90618   M   0.570     0.490   0.145        0.8740          0.3525   
4       90619   I   0.415     0.325   0.110        0.3580          0.1575   
...       ...  ..     ...       ...     ...           ...             ...   
60406  151021   I   0.345     0.260   0.085        0.1775          0.0735   
60407  151022   F   0.525     0.410   0.145        0.8445          0.3885   
60408  151023   I   0.590     0.440   0.155        1.1220          0.3930   
60409  151024   F   0.660     0.525   0.190        1.4935          0.5885   
60410  151025   F   0.430     0.340   0.120        0.4150          0.1525   

       Whole weight.2  Shell weight      Rings  
0              0.3125     

In [ ]:
submission_data = test_data[['id', 'Rings']]
submission_data.loc[submission_data['Rings'] < 0, 'Rings'] = 0
submission_data.to_csv('sub1.csv', index = False)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
train_data['Sex'] = le.fit_transform(train_data['Sex'])
print(train_data)

          id  Sex  Length  Diameter  Height  Whole weight  Whole weight.1  \
0          0    0   0.550     0.430   0.150        0.7715          0.3285   
1          1    0   0.630     0.490   0.145        1.1300          0.4580   
2          2    1   0.160     0.110   0.025        0.0210          0.0055   
3          3    2   0.595     0.475   0.150        0.9145          0.3755   
4          4    1   0.555     0.425   0.130        0.7820          0.3695   
...      ...  ...     ...       ...     ...           ...             ...   
90610  90610    2   0.335     0.235   0.075        0.1585          0.0685   
90611  90611    2   0.555     0.425   0.150        0.8790          0.3865   
90612  90612    1   0.435     0.330   0.095        0.3215          0.1510   
90613  90613    1   0.345     0.270   0.075        0.2000          0.0980   
90614  90614    1   0.425     0.325   0.100        0.3455          0.1525   

       Whole weight.2  Shell weight  Rings  
0              0.1465        0

In [ ]:
cols = train_data.columns.drop('Rings')
MS_x = MS(cols).fit(train_data)
x = MS_x.transform(train_data)
y = train_data['Rings']
model = sm.OLS(y,x)
result = model.fit()
summarize(result)

coef       std err        t  P>|t|
intercept       2.830600e+00  5.600000e-02   50.708  0.000
id             -4.985000e-07  2.550000e-07   -1.952  0.051
Sex             2.220000e-02  8.000000e-03    2.634  0.008
Length         -2.520100e+00  4.040000e-01   -6.236  0.000
Diameter        9.745400e+00  5.000000e-01   19.492  0.000
Height          2.238970e+01  4.900000e-01   45.684  0.000
Whole weight    3.859700e+00  1.210000e-01   31.791  0.000
Whole weight.1 -1.611480e+01  1.510000e-01 -106.626  0.000
Whole weight.2 -6.303700e+00  2.960000e-01  -21.305  0.000
Shell weight    2.096150e+01  2.200000e-01   95.453  0.000

In [ ]:
test_data = pd.read_csv("test.csv")
test_data['Sex'] = le.fit_transform(test_data['Sex'])
new_x = MS_x.transform(test_data)
pred = result.get_prediction(new_x)
pred.predicted_mean

array([ 8.44419115,  9.89733147, 10.0841702 , ..., 11.34061573,
       13.60811691,  8.13959527])

In [ ]:
test_data['Rings'] = pred.predicted_mean
print(test_data)

           id  Sex  Length  Diameter  Height  Whole weight  Whole weight.1  \
0       90615    2   0.645     0.475   0.155        1.2380          0.6185   
1       90616    2   0.580     0.460   0.160        0.9830          0.4785   
2       90617    2   0.560     0.420   0.140        0.8395          0.3525   
3       90618    2   0.570     0.490   0.145        0.8740          0.3525   
4       90619    1   0.415     0.325   0.110        0.3580          0.1575   
...       ...  ...     ...       ...     ...           ...             ...   
60406  151021    1   0.345     0.260   0.085        0.1775          0.0735   
60407  151022    0   0.525     0.410   0.145        0.8445          0.3885   
60408  151023    1   0.590     0.440   0.155        1.1220          0.3930   
60409  151024    0   0.660     0.525   0.190        1.4935          0.5885   
60410  151025    0   0.430     0.340   0.120        0.4150          0.1525   

       Whole weight.2  Shell weight      Rings  
0             

In [ ]:
submission_data = test_data[['id', 'Rings']]
submission_data.loc[submission_data['Rings'] < 0, 'Rings'] = 0
submission_data.to_csv('sub2.csv', index = False)

In [ ]:
cols = train_data.columns.drop(['id','Rings'])
MS_x = MS(cols).fit(train_data)
x = MS_x.transform(train_data)
y = train_data['Rings']
model = sm.OLS(y,x)
result = model.fit()
summarize(result)

coef  std err        t  P>|t|
intercept        2.8081    0.055   51.412  0.000
Sex              0.0222    0.008    2.640  0.008
Length          -2.5226    0.404   -6.242  0.000
Diameter         9.7496    0.500   19.500  0.000
Height          22.3870    0.490   45.678  0.000
Whole weight     3.8593    0.121   31.787  0.000
Whole weight.1 -16.1141    0.151 -106.621  0.000
Whole weight.2  -6.3031    0.296  -21.303  0.000
Shell weight    20.9607    0.220   95.448  0.000

In [ ]:
test_data = pd.read_csv("test.csv")
test_cols = test_data.columns.drop('id')
test_data2 = test_data[test_cols]
test_data2['Sex'] = le.fit_transform(test_data2['Sex'])
new_x = MS_x.transform(test_data2)
pred = result.get_prediction(new_x)
pred.predicted_mean

<ipython-input-114-baf372090c29>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data2['Sex'] = le.fit_transform(test_data2['Sex'])


array([ 8.46679905,  9.91999442, 10.10674879, ..., 11.39313018,
       13.66061146,  8.1923116 ])

In [ ]:
test_data['Rings'] = pred.predicted_mean
print(test_data)

           id Sex  Length  Diameter  Height  Whole weight  Whole weight.1  \
0       90615   M   0.645     0.475   0.155        1.2380          0.6185   
1       90616   M   0.580     0.460   0.160        0.9830          0.4785   
2       90617   M   0.560     0.420   0.140        0.8395          0.3525   
3       90618   M   0.570     0.490   0.145        0.8740          0.3525   
4       90619   I   0.415     0.325   0.110        0.3580          0.1575   
...       ...  ..     ...       ...     ...           ...             ...   
60406  151021   I   0.345     0.260   0.085        0.1775          0.0735   
60407  151022   F   0.525     0.410   0.145        0.8445          0.3885   
60408  151023   I   0.590     0.440   0.155        1.1220          0.3930   
60409  151024   F   0.660     0.525   0.190        1.4935          0.5885   
60410  151025   F   0.430     0.340   0.120        0.4150          0.1525   

       Whole weight.2  Shell weight      Rings  
0              0.3125     

In [ ]:
submission_data = test_data[['id', 'Rings']]
submission_data.loc[submission_data['Rings'] < 0, 'Rings'] = 0
submission_data.to_csv('sub3.csv', index = False)